# Практическая работа 2

Для выполнения заданий данной практической работы, необходимо
воспользоваться сторонними библиотеками `numpy` и `pandas`:

In [1]:
import numpy as np
import pandas as pd

## Задание 1

Напишите программу, которая считывает с консоли числа (по одному в строке)
до тех пор, пока сумма введённых чисел не будет равна 0 и после этого
выводит сумму квадратов всех считанных чисел.

Сначала напишем функцию для решения задачи:

In [2]:
from typing import Callable


# noinspection PyShadowingNames
def task_1(factory: Callable[[], float] = lambda: float(input())) -> list[float]:
    nums = []
    while True:
        result = factory()
        nums.append(result)
        if sum(nums) == 0:
            return nums

Затем сам запускаемый скрипт:

In [3]:
def factory() -> float:
    try:
        return float(input('Введите число: '))
    except ValueError:
        print('Неверный ввод! Необходимо вводить именно числа!!!')
        return factory()

print('Введите числа по одному на строке')
nums = task_1(factory)
print(f'Введенные числа: {nums}')
print(f'Сумма их квадратов: {sum(x**2 for x in nums)}')

Введите числа по одному на строке
Введенные числа: [-1.0, 1.0]
Сумма их квадратов: 2.0


## Задание 2

Напишите программу, которая выводит последовательность чисел,
длинною N, где каждое число повторяется столько раз, чему оно равно.
На вход программе передаётся неотрицательное целое число N.

Например, если N = 7, то программа должна вывести `1 2 2 3 3 3 4`. Вывод
элементов списка через пробел – `print(*list)`.

Сначала напишем функцию для решения задачи:

In [4]:
# noinspection PyShadowingNames
def task_2(n: int) -> list[int]:
    nums = [0] * n
    current, count = 1, 0
    for i in range(n):
        if count == current:
            current += 1
            count = 0
        nums[i] = current
        count += 1
    return nums

Затем сам запускаемый скрипт:

In [5]:
try:
    n = int(input('Введите длину последовательности: '))
    nums = task_2(n)
    print('Получившаяся последовательность:', *nums)
except ValueError:
    print('Необходимо ввести целочисленное число!')

Получившаяся последовательность: 1 2 2 3 3 3 4


## Задание 3

Матрицу произвольного размера вытянуть в один вектор, не применяя
встроенные методы Python. Пример:

![Пример](task-3.png)

Для создания матрицы можно использовать `np.random.rand(кол-во строк, кол-во столбцов)`.

Сначала напишем функцию для решения задачи:

In [6]:
# noinspection PyShadowingNames
def task_3(matrix: list) -> list:
    return [item for row in matrix for item in row]

Затем сам запускаемый скрипт:

In [7]:
try:
    rows = int(input('Введите число строк матрицы: '))
    columns = int(input('Введите число столбцов матрицы: '))
    matrix = np.random.rand(rows, columns)
    print(f"Исходная матрица {rows}x{columns}:", matrix, sep='\n', end='\n\n')
    print(f"Результат — вытянутый вектор в {rows}x{columns}={rows * columns} элементов:", task_3(matrix), sep='\n')
except ValueError:
    print('Необходимо ввести целые числа!')

Исходная матрица 4x5:
[[0.3997809  0.35009943 0.00374421 0.91216325 0.18144477]
 [0.62693054 0.73834913 0.43244623 0.64409071 0.22409519]
 [0.06110247 0.85338614 0.89997565 0.67894673 0.74488785]
 [0.82798114 0.57479843 0.94138073 0.89649212 0.87676101]]

Результат — вытянутый вектор в 4x5=20 элементов:
[0.39978089996617283, 0.35009942719778164, 0.003744211708780587, 0.9121632534890141, 0.18144477036741358, 0.6269305447150395, 0.7383491302786143, 0.43244623399614857, 0.6440907104143582, 0.22409519073409512, 0.06110246946182896, 0.8533861394063028, 0.8999756497064734, 0.6789467301289462, 0.7448878548658572, 0.8279811373078044, 0.5747984343426413, 0.9413807346887707, 0.8964921186308241, 0.8767610144641647]


## Задание 4

Даны два списка:

```
А = [1, 2, 3, 4, 2, 1, 3, 4, 5, 6, 5, 4, 3, 2]

В = ['a', 'b', 'c', 'c', 'c', 'b', 'a', 'c', 'a', 'a', 'b', 'c', 'b', 'a']
```

Создать словарь, в котором ключи – это содержимое списка В, а
значения для ключей словаря – это сумма всех элементов списка А в
соответствии с буквой, содержащийся на той же позиции в списке В.

Пример результата программы: `{'a' : 10, 'b' : 15, 'c' : 6}`.

Сначала напишем функцию для решения задачи:

In [8]:
# noinspection PyShadowingNames
def task_4(a: list[int], b: list[str]) -> dict[str, int]:
    result = {}
    for a, b in zip(a, b):
        if b not in result:
            result[b] = 0
        result[b] += a
    return result

Затем сам запускаемый скрипт:

In [9]:
a = [1, 2, 3, 4, 2, 1, 3, 4, 5, 6, 5, 4, 3, 2]
b = ['a', 'b', 'c', 'c', 'c', 'b', 'a', 'c', 'a', 'a', 'b', 'c', 'b', 'a']
assert len(a) == len(b)
result = task_4(a, b)
print(f'Результат выполнения алгоритма: {result}')

Результат выполнения алгоритма: {'a': 17, 'b': 11, 'c': 17}


## Задание 5

Скачать и загрузить данные о стоимости домов в Калифорнии, используя библиотеку sklearn.

![Картинка](task-5.png)

In [10]:
from sklearn.datasets import fetch_california_housing

data = fetch_california_housing(as_frame=True)
data

{'data':        MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
 0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
 1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
 2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
 3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
 4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
 ...       ...       ...       ...        ...         ...       ...       ...   
 20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
 20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
 20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
 20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
 20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   
 
        Longitude 

## Задание 6

Используя метод `pd.concat([датафрейм1, датафрейм2], axis = 1)`,
добавить к данным столбец, содержащий информацию о медианной
стоимости дома (`.target` и `.target_names`).

In [11]:
data = pd.concat([data.data, data.target], axis=1)
data.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  MedHouseVal  
0    -122.23        4.526  
1    -122.22        3.585  
2    -122.24        3.521  
3    -122.25        3.413  
4    -122.25        3.422

## Задание 7

Использовать метод info().

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MedInc       20640 non-null  float64
 1   HouseAge     20640 non-null  float64
 2   AveRooms     20640 non-null  float64
 3   AveBedrms    20640 non-null  float64
 4   Population   20640 non-null  float64
 5   AveOccup     20640 non-null  float64
 6   Latitude     20640 non-null  float64
 7   Longitude    20640 non-null  float64
 8   MedHouseVal  20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB


## Задание 8

Узнать, есть ли пропущенные значения, используя `isna().sum()`.

In [13]:
data.isna().sum()

MedInc         0
HouseAge       0
AveRooms       0
AveBedrms      0
Population     0
AveOccup       0
Latitude       0
Longitude      0
MedHouseVal    0
dtype: int64

## Задание 9

Вывести записи, где средний возраст домов в районе более 50 лет и
население более 2500 человек, используя метод `loc()`.

In [14]:
data.loc[(data.HouseAge > 50) & (data.Population > 2500)]

MedInc  HouseAge  AveRooms  AveBedrms  Population    AveOccup  \
460    1.4012      52.0  3.105714   1.060000      3337.0    9.534286   
4131   3.5349      52.0  4.646119   1.047945      2589.0    5.910959   
4440   2.6806      52.0  4.806283   1.057592      3062.0    4.007853   
5986   1.8750      52.0  4.500000   1.206349      2688.0   21.333333   
7369   3.1901      52.0  4.730942   1.017937      3731.0    4.182735   
8227   2.3305      52.0  3.488860   1.170380      3018.0    3.955439   
13034  6.1359      52.0  8.275862   1.517241      6675.0  230.172414   
15634  1.8295      52.0  2.628169   1.053521      2957.0    4.164789   
15652  0.9000      52.0  2.237474   1.053535      3260.0    2.237474   
15657  2.5166      52.0  2.839075   1.184049      3436.0    1.621520   
15659  1.7240      52.0  2.278566   1.082348      4518.0    1.780142   
15795  2.5755      52.0  3.402576   1.058776      2619.0    2.108696   
15868  2.8135      52.0  4.584329   1.041169      2987.0    3.966799   

       Latitude  Longitude  MedHouseVal  
460       37.87    -122.26      1.75000  
4131      34.13    -118.20      1.93600  
4440      34.08    -118.21      1.53000  
5986      34.10    -117.71      2.12500  
7369      33.97    -118.21      1.67600  
8227      33.78    -118.20      1.62500  
13034     38.69    -121.15      2.25000  
15634     37.80    -122.41      2.43800  
15652     37.80    -122.41      5.00001  
15657     37.79    -122.41      2.75000  
15659     37.79    -122.41      2.25000  
15795     37.77    -122.42      3.25000  
15868     37.76    -122.41      2.60300

## Задание 10

Узнать максимальное и минимальное значения медианной стоимости дома `(max(), min())`.

In [15]:
data.MedHouseVal.max(), data.MedHouseVal.min()

(5.00001, 0.14999)

## Задание 11

Используя метод `apply()`, вывести на экран название признака и его среднее значение.

In [16]:
data.apply(lambda x: x.mean())

MedInc            3.870671
HouseAge         28.639486
AveRooms          5.429000
AveBedrms         1.096675
Population     1425.476744
AveOccup          3.070655
Latitude         35.631861
Longitude      -119.569704
MedHouseVal       2.068558
dtype: float64